ALTER TABLE magasin ADD COLUMN couleur_primaire VARCHAR(7) NOT NULL DEFAULT '#3B6B3E';
ALTER TABLE magasin ADD COLUMN couleur_secondaire VARCHAR(7) NOT NULL DEFAULT '#B23A2E';
ALTER TABLE magasin ADD COLUMN logo_url VARCHAR(500);